version: '3'
services:
  # portainer:
  #   container_name: portainer
  #   restart: always
  #   environment:
  #     - TZ=${TZ}
  #   ports:
  #     - 9000:9000
  #   image: ${PORTAINER}

  # pia:
  #   container_name: pia
  #   restart: always
  #   networks:
  #     - pia_network
  #   cap_add:
  #     - NET_ADMIN
  #   devices:
  #     - /dev/net/tun
  #   dns:
  #     - 209.222.18.222
  #     - 209.222.18.218
  #   environment:
  #     - REGION=${PIA_REGION}
  #     - USERNAME=${PIA_USERNAME}
  #     - PASSWORD=${PIA_PASSWORD}
  #   image: ${PIA}

  # transmission:
  #   container_name: transmission
  #   depends_on:
  #     - pia
  #   restart: always
  #   networks:
  #     - pia_network
  #   ports:
  #     - 9091:9091
  #     - 51413:51413
  #     - 51413:51413/udp
  #   volumes:
  #     - /${MNT}/config/transmission:/config
  #     - /${MNT}/downloads:/downloads
  #     - /${MNT}/downloads/watch:/watch
  #     - /${MNT}/downloads/complete:/downloads/complete
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #   image: ${TRANSMISSION}

  transmission:
    container_name: transmission
    build:
      context: .
      dockerfile: Dockerfile.armhf
    image: haugene/rpi-transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    restart: always
    networks:
      - transmission_network
    ports:
      - "9091:9091"
      - "8888:8888"
    dns:
      - 209.222.18.222
      - 209.222.18.218
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MNT}/downloads/:/data
    environment:
      - PUID=1000 
      - PGID=1000
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_USERNAME=${PIA_USERNAME}
      - OPENVPN_PASSWORD=${PIA_PASSWORD}
      - OPENVPN_CONFIG=${PIA_REGION}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - TRANSMISSION_WEB_UI=${TRANSMISSION_WEB_UI} 

  proxy:
    container_name: transmission-proxy
    restart: always
    build:
      context: ./proxy
      dockerfile: Dockerfile.armhf
    depends_on:
      - transmission
    networks:
      - transmission_network
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    image: haugene/rpi-transmission-openvpn-proxy

  jackett:
    container_name: jackett
    depends_on:
      - transmission
    restart: always
    networks:
      - transmission_network
    ports:
      - '9117:9117'
    volumes:
      - '${MNT}/config/jackett:/config'
      - '${MNT}/downloads:/downloads'
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    image: ${JACKETT}

  sonarr:
    container_name: sonarr
    depends_on:
      - jackett
      - transmission
    restart: always
    networks:
      - transmission_network
    ports:
      - '8989:8989'
    volumes:
      - '${MNT}/config/sonarr:/config'
      - '${MNT}/data/tv:/tv'
      - '${MNT}/downloads:/downloads'
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    image: ${SONARR}  
    
  radarr:
    container_name: radarr
    depends_on:
      - jackett
      - transmission
    restart: always
    networks:
      - transmission_network
    ports:
      - '7878:7878'
    volumes:
      - '${MNT}/config/radarr:/config'
      - '${MNT}/data/movies:/movies'
      - '${MNT}/downloads:/downloads'
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    image: ${RADARR}

  # headphones:
  #   container_name: headphones
  #   depends_on:
  #     - jackett
  #     - transmission
  #   restart: always
  #   networks:
  #     - transmission_network
  #   ports:
  #     - '8118 :8181 '
  #   volumes:
  #     - '/${MNT}/config/headphones:/config'
  #     - '/${MNT}/data/music:/music'
  #     - '/${MNT}/downloads:/downloads'
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #   image: ${HEADPHONES}

  # ombi:
  #   container_name: ombi
  #   restart: always
  #   networks:
  #     - transmission_network
  #   volumes:
  #     - '/${MNT}/config/ombi:/config'
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #   ports:
  #     - '3579:3579'
  #   image: ${OMBI}

  # nginx:
  #   container_name: web
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   networks:
  #     - pia_network
  #   # links:
  #   #   - 'pia:transmission'
  #   #   - 'pia:jackett'
  #   #   - 'pia:radarr'
  #   #   - 'pia:sonarr'
  #   #   - 'pia:headphones'
  #   #   - 'pia:ombi'
  #   image: ${NGINX}

  # plex:
  #   container_name: plex
  #   restart: always
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #   volumes:
  #     - '/${MNT}/config/plex:/config'
  #     - '/${MNT}/data/tv:/data/tv'
  #     - '/${MNT}/data/movies:/data/movies'
  #     - '/${MNT}/data/music:/data/music'
  #   ports:
  #     - '32400:32400'
  #     - '32400:32400/udp'
  #     - '32469:32469'
  #     - '32469:32469/udp'
  #     - '5354:5353/udp'
  #     - '1900:1900/udp'
  #   image: ${PLEX}

  # tautulli:
  #   container_name: tautulli
  #   restart: always
  #   depends_on:
  #     - plex
  #   volumes:
  #     - '/${MNT}/config/tautulli:/config'
  #     - '/${MNT}/config/tautulli/logs:/logs:ro'
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #   ports:
  #     - '8112:8181'
  #   image: ${TAUTULLI}

  # heimdall:
  #   container_name: heimdall
  #   restart: always
  #   volumes:
  #     - '/${MNT}/config/heimdall:/config'
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #   ports:
  #     - 80:80
  #     - 443:443
  #   image: ${HEIMDALL}

networks:
  transmission_network: