version: "3"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    environment:
      - TZ=${TZ}
    ports:
      - 9000:9000
    restart: unless-stopped

  plex:
    container_name: plex
    image: linuxserver/plex
    environment:
      - VERSION=latest
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    networks:
      - host
    volumes:
      - ./config/plex:/config
      - ./media/tv:/data/tv
      - ./media/movies:/data/movies
      - ./media/music:/data/music
    restart: unless-stopped

  plexpy:
    container_name: plexpy
    image: linuxserver/plexpy
    depends_on:
      - plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
        - 8181:8181
    volumes:
        - ./config/plexpy:/config
        - ./config/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
    restart: unless-stopped

  ombi:
    container_name: ombi
    image: linuxserver/ombi
    depends_on:
      - plex
    ports:
        - 3579:3579
    environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
    volumes:
        - ./config/ombi:/config
    restart: unless-stopped

  nginx:
    container_name: web
    image: dperson/nginx
    networks:
      - service:pia
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  pia:
    container_name: pia
    image: colinhebert/pia-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    environment:
      - USERNAME=${PIA_USERNAME}
      - PASSWORD=${PIA_PASSWORD}
      - REGION=${PIA_REGION}
      - TZ=${TZ}
    networks:
      - pia
    restart: unless-stopped

  transmission:
    container_name: transmission
    image: linuxserver/transmission
    depends_on:
      - pia
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    networks:
      - service:pia
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - ./config:/config
      - ./downloads:/downloads
      - ./downloads/watch:/watch
      - ./downloads/complete:/downloads/complete
    restart: unless-stopped

  jackett:
    container_name: jackett
    image: linuxserver/jackett
    depends_on:
      - pia
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    networks:
      - service:pia
    ports:
      - 9117:9117
    volumes:
      - ./config/jackett:/config
      - ./downloads:/downloads
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    depends_on:
      - pia
      - transmission
      - jackett
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    networks:
      - service:pia
    ports:
      - 8989:8989
    volumes:
      - ./config/sonarr:/config
      - ./media/tv:/tv
      - ./media/movies:/movies
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    depends_on:
      - pia
      - transmission
      - jackett
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    networks:
      - service:pia
    ports:
      - 7878:7878
    volumes:
      - ./config/radarr:/config
      - ./downloads:/downloads
      - ./media/movies:/movies
    restart: unless-stopped

  headphones:
    container_name: headphones
    image: linuxserver/headphones
    depends_on:
      - pia
      - transmission
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    networks:
      - service:pia
    ports:
      - 8181:8181
    volumes:
      - ./config/headphones:/config
      - ./downloads:/downloads
      - ./media/music:/music
    restart: unless-stopped

  netdata:
    container_name: netdata
    image: titpetric/netdata
    ports:
        - 19999:19999
    cap_add:
        - SYS_PTRACE
    volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  # pihole:
  #   container_name: pihole
  #   image: diginc/pi-hole:alpine
  #   environment:
  #     - ServerIP=${HOST_IP}
  #     - TZ=${TZ}
  #     - WEBPASSWORD=${PIHOLE_PASSWORD}
  #   volumes:
  #     - /root/pihole/:/etc/pihole/
  #     - /root/pihole/dnsmasq.d/:/etc/dnsmasq.d/
  #   ports:
  #     - "80:80"
  #     - "53:53/tcp"
  #     - "53:53/udp"
  #   restart: unless-stopped
